### ISSUE TITLE
Nuxt v3.0.0 release appears to have broken the Storyblok integration

### ISSUE THREAD

**Issue by chrisnoden** [storyblok/storyblok-nuxt#234]
Updated my project to use the release (stable) of v3.0.0 of Nuxt and things are broken:

```
ERROR  Cannot start nuxt:  (0 , _kit.addAutoImport) is not a function                                                                                                                             15:38:53

  at node_modules/@storyblok/nuxt/src/module.js:50:28
  at Array.forEach (<anonymous>)                                                                                                                                                                   15:38:52
  at setup (node_modules/@storyblok/nuxt/src/module.js:49:11)
  at normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:29)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1823:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

**Comment by filipecruz** [comment]
Facing same issue

**Comment by chrisnoden** [comment]
Weirdly, it works in rc14 and I can't see any BCs in v3.0.0 release notes. (Mind you, the nuxt team releasing BCs during release candidate is not cool - rant over)

**Comment by chrisnoden** [comment]
I can confirm hacking the above block in `src/module.js` to become:
```
import {
  defineNuxtModule,
  addPlugin,
  addComponentsDir,
  addImports as addAutoImport,
  addImportsDir as addAutoImportDir
} from "@nuxt/kit";
```
and Nuxt now builds. Storyblok works.
Now, I've never done a PR to a project, but I might try

**Comment by alvarosabu** [comment]
Wow that was fast haha

I just updated my portfolio and worked, I do have a weird error on the console regarding the ApiClient tho:

```
storyblok-vue.mjs:655 You can't use useStoryblokApi if you're not loading apiPlugin. Please provide it on StoryblokVue initialization.
```

**Comment by chrisnoden** [comment]
My first ever PR. Probably wrong: https://github.com/storyblok/storyblok-nuxt/pull/235

@alvarosabu in your `nuxt.config.ts` under `modules` you ned to add `useApiClient: true` to the storyblok module, eg

```
        ['@storyblok/nuxt', {
            accessToken: process.env.STORYBLOK_ACCESS_TOKEN,
            useApiClient: true,
            apiOptions: { cache: { type: 'memory' } }
        }],
```

You may also find that the first build on nuxt after an upgrade to change to the node_modules may result in Storyblok not working properly. (cough). Just CTRL+C then `yarn dev` again (or your preferred way of starting the dev server). You tend to see this problem in the browser not the terminal.

**Comment by alvarosabu** [comment]
@chrisnoden that's the funny part, I have it already 😂

**Comment by alvarosabu** [comment]
I deleted node modules and install all again, now I'm facing same issue as you

**Comment by chrisnoden** [comment]
For now, until Storyblok patch their code, you might have to pin your nuxt version:

In package.json:
`"nuxt": "3.0.0-rc.14",`

It appears to have pretty much all of the v3.0.0 changes apart from the removal of the deprecated functions that Storyblok is using.

**Comment by patrykkurzeja91** [comment]
@alvarosabu just curious - what axios version do You use?

**Comment by LucaMargadant** [comment]
@chrisnoden Thanks for looking into this! 

Actually rc-14 is not working. At one of the last [commits](https://github.com/nuxt/framework/pull/9010/commits/a9c1d0456c8de3ec34be48d2672ec45ace1f8990) into rc-14 before 3.0.0 was released the deprecated modules were been removed from rc-14. 

For everyone facing the issue too, you have to go back to rc-13 until this is fixed.

**Comment by lavellotron** [comment]
Same issue here. I rolled back to rc12 for both `nuxt` and `@nuxt/kit` - trying to build a client website.

https://github.com/nuxt/framework/issues/9063

**Comment by codeflorist** [comment]
v4.5.0 is out and has solved the problem.

**Comment by alvarosabu** [comment]
@codeflorist  I installed the 4.5.0 and still have the error

```
storyblok-vue.mjs:655 You can't use useStoryblokApi if you're not loading apiPlugin. Please provide it on StoryblokVue initialization
```

I also have 

```
 [
      '@storyblok/nuxt',
      {
        accessToken: process.env.STORYBLOK_API_TOKEN,
        useApiClient: true,
      },
    ],
```

**Comment by chrisnoden** [comment]
@alvarosabu I get this a lot. If you CTRL+C the terminal and then restart the nuxt dev server it clears. I don't know why (in dev only) I need to start twice for SB to work properly.

**Comment by alvarosabu** [comment]
@chrisnoden  yeah but I cant do that on the pipelines xD, I tried several times still the same error

**Comment by chrisnoden** [comment]
@alvarosabu This is a "feature" with current SB until they get their next major release out. They haven't pinned axios in their bundle. You need to pin axios in your package.json

`"axios": "^0.27.2"`

**Comment by alvarosabu** [comment]
@chrisnoden ok so v1 fo Axios is going to break, Axios issue gone but an error on the console for `useStoryblokApi` still there

**Comment by chrisnoden** [comment]
> 

For my staging pipeline I ensure I'm not building a dev env.

`nuxt build`
`node .output/server/index.mjs`

**Comment by patrykkurzeja91** [comment]
@alvarosabu try with `npx nuxi clean` - You can also try to rebuild `node_modules`

**Comment by SebbeJohansson** [comment]
@chrisnoden you are a god damn saviour. Adding `useApiClient: true` was the only thing that worked. Cleaning, reinstalling etc did not work. It might have to do with me using `useAsyncStoryblok`... Not sure.

**Comment by lavellotron** [comment]
My issue is fixed once I updated `@storyblok/nuxt` to `v4.5.0`. Thanks for the speedy release! ❤️

**Comment by alexjoverm** [comment]
Yes, please update to latest `v4.5.0`. We released the fix for stable Nuxt last thrusday. Feel free to reopen if you still have it

**Comment by SebbeJohansson** [comment]
@jamaluddinrumi I have seen that error ("you can't use useStoryblockApi") in my nuxt3 application with yarn. But it goes away after resaving the nuxt.config.ts which is super weird. I haven't bothered researching it more yet.

**Comment by jamaluddinrumi** [comment]
> @jamaluddinrumi I have seen that error ("you can't use useStoryblockApi") in my nuxt3 application with yarn. But it goes away after resaving the nuxt.config.ts which is super weird. I haven't bothered researching it more yet.

![Screen Shot 2022-12-23 at 11 51 15 PM](https://user-images.githubusercontent.com/446780/209372321-6f60f005-db9c-4e13-b805-8d6b050ecff4.png)
sometimes it works on development but it will always generating error on production.

**Comment by jamaluddinrumi** [comment]
but it always works when using `npx nuxi` directly without yarn nor pnpm for dev even for production

**Comment by SebbeJohansson** [comment]
Hmm okay. When i get the chance I will make an issue about this specifically.
