### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client when trying to setup redirects + handle 404

### ISSUE THREAD

**Issue by m0zz094** [storyblok/storyblok-nuxt#353]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

I created a [minimal repo](https://github.com/m0zz094/storyblok-redirects-404) here to show what's happening.

I created a global middleware to handle 301 redirects that should work like that:

- When someone visits any url mapped inside **redirects/redirects.js**, they should 301 redirects to the "dst" url
- When someone visits any url that ends with a trailing slash (exept the homepage) they should redirect to the same url without the trailing slash (example: **/products/** redirects to **/products**)

If you visit **/example** you'll be redirected correctly to **/example/redirect**
If you try to visit any random url that ends with a trailing slash (example: **/asgasg/asgasg/**) you'll get an error like that:

`[nitro] [dev] [unhandledRejection] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client                                                                   20:15:52
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.setHeader (node:_http_outgoing:576:11)
    at setResponseHeader (file:///C:/Users/fmozz/Desktop/WEB/storyblok-redirects-404/node_modules/h3/dist/index.mjs:670:18)
    at Object.errorhandler [as onError] (file:///C:/Users/fmozz/Desktop/WEB/storyblok-redirects-404/.nuxt/dev/index.mjs:484:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.toNodeHandle (file:///C:/Users/fmozz/Desktop/WEB/storyblok-redirects-404/node_modules/h3/dist/index.mjs:1329:9) {
  code: 'ERR_HTTP_HEADERS_SENT'
}`

It's been weeks without understanding what could be the problem here.

Any Idea?

**Comment by m0zz094** [comment]
For anyone struggling with this, I replaced nuxt middleware that handles trailing slash + redirects with vercel.json

`
{
  "trailingSlash": false,
  "redirects": [
    {
      "source": "/example",
      "destination": "/example/redirect",
      "statusCode: 301
  ]
}
`

**Comment by m0zz094** [comment]
Hi @alvarosabu, yes, this was fixed with version 3.4.1 of nuxt, thanks!
