### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'status') 

### ISSUE THREAD

**Issue by jamaluddinrumi** [storyblok/storyblok-nuxt#357]
```
TypeError: Cannot read properties of undefined (reading 'status')
    at U (index.53285a74.js:1:2702)
    at async setup (index.53285a74.js:1:3081)
```
story is not loaded at all.

everything is fine both running `nuxt dev` & `nuxt generate` in local development, but always fails when running `nuxt generate` in production.

live: https://6702f5bc.hnh-cookies.pages.dev/

![Screen Shot 2023-04-05 at 3 47 13 AM](https://user-images.githubusercontent.com/446780/229918267-b7db0167-6ef6-4861-b229-a59eda6c075d.png)

## Steps to Reproduce

1. clone https://github.com/jamaluddinrumi/hnh-cookies
2. deploy with the default `nuxt generate` in cloudflare pages

**Comment by jamaluddinrumi** [comment]
solved by changing access token to `Preview` level.
