### ISSUE TITLE
Error while requiring module @storyblok/nuxt

### ISSUE THREAD

**Issue by lalit-sharemil** [storyblok/storyblok-nuxt#514]
### Describe the issue you're facing

I just installed a fresh Nuxt 3 project and added `@storyblok/nuxt@5.6.0` but the project does not start.

Even the demo project has the same issue.

### Reproduction

https://stackblitz.com/edit/nuxt-3-sdk-demo

### Steps to reproduce

- `npx nuxi@latest init project`
- `cd project`
- `npm install @storyblok/nuxt`
- `npm run dev`

### System Info

```shell
- Macos Ventura 13.4.1
- nuxt 3.6.5
- @storyblok/nuxt 5.6.0
```

### Used Package Manager

npm

### Error logs (Optional)

```
 ERROR  Error while requiring module @storyblok/nuxt: Error: Cannot find module '/Users/username/project/@storyblok/nuxt'   10:31:12 PM
Require stack:
- /Users/username/project/index.js


 ERROR  Cannot start nuxt:  Cannot find module '/Users/username/project/@storyblok/nuxt'                                    10:31:12 PM
Require stack:
- /Users/username/project/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:250100)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2230:29)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2240:24)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2435:90)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2408:47)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3238:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:205:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:249:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:49:20)
```

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by bbommarito** [comment]
I can also confirm this issue.

I followed the directions from this repository. I tried with both `pnpm` and then `npm` thinking that maybe `pnpm` was being weird. No difference. NPM and PNPM exhibit the same behavior.

```[4:21:36 PM]  ERROR  Error while requiring module @storyblok/nuxt: Error: Cannot find module '/home/bbommarito/github/storyblok-test/@storyblok/nuxt'
Require stack:
- /home/bbommarito/github/storyblok-test/index.js


 ERROR  Cannot start nuxt:  Cannot find module '/home/bbommarito/github/storyblok-test/@storyblok/nuxt'     4:21:36 PM
Require stack:
- /home/bbommarito/github/storyblok-test/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
  at Function.resolve (node:internal/modules/helpers:136:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/jiti@1.19.1/node_modules/jiti/dist/jiti.js:1:250100)
  at resolveModule (node_modules/.pnpm/@nuxt+kit@3.6.5/node_modules/@nuxt/kit/dist/index.mjs:2230:29)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.6.5/node_modules/@nuxt/kit/dist/index.mjs:2240:24)
  at loadNuxtModuleInstance (node_modules/.pnpm/@nuxt+kit@3.6.5/node_modules/@nuxt/kit/dist/index.mjs:2435:90)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.6.5/node_modules/@nuxt/kit/dist/index.mjs:2408:47)
  at async initNuxt (node_modules/.pnpm/nuxt@3.6.5_@types+node@18.17.4/node_modules/nuxt/dist/index.mjs:3238:7)
  at async load (node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/chunks/dev.mjs:205:9)                 4:21:35 PM
  at async Object.invoke (node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/chunks/dev.mjs:249:5)
  at async _main (node_modules/.pnpm/nuxi@3.6.5/node_modules/nuxi/dist/cli.mjs:49:20)```

**Comment by wspitz** [comment]
I can confirm as well, I used yarn and got exactly the same errors with nuxt3 and @storyblok/nuxt.

**Comment by eggnstone** [comment]
Same here.
Downgrade to 5.5.2 works.

**Comment by chrisnoden** [comment]
The issue is triggered with nuxt v3.6.4 or v3.6.5 - it is not a problem using nuxt v3.6.3

**Comment by sgc-fireball** [comment]
+1 with ^5.5.2 and nuxt ^3.6.1
