### ISSUE TITLE
Cannot read properties of undefined (reading '_uid')

### ISSUE THREAD

**Issue by telisjok** [storyblok/storyblok-nuxt#69]
### Environment

```
Nuxt CLI v3.0.0-27333638.5ab1816
RootDir: C:\JavascriptProjects\NUXT\website-ui
Nuxt project info:

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.13.1`
- Nuxt Version:     `3.0.0-27333638.5ab1816`
- Package Manager:  `npm@8.3.0`
- Bundler:          `Vite`
- User Config:      `build`, `components`, `css`, `modules`, `vue`
- Runtime Modules:  `@storyblok/nuxt@3.0.0-beta.1`
- Build Modules:    `-`
------------------------------
```

### The bug

I am trying to read the component's attributes (that are defined in Storyblok Schema) but I am getting `Cannot read properties of undefined (reading '_uid')`

```
{
  "story": {
    "name": "Home",
    "created_at": "2021-12-15T14:19:10.139Z",
    "published_at": null,
    "id": 92562831,
    "uuid": "44d6e4a4-00d9-4bc5-9662-de43d14e4bc2",
    "content": {
      "_uid": "6fac4f51-4f36-4e51-9855-0d192d27bfef",
      "body": [
        {
          "_uid": "05cdec92-ac74-4112-aef2-6886f5698174",
          "component": "section",
          "isFullWidth": false,
          "_editable": "<!--#storyblok#{\"name\": \"section\", \"space\": \"139507\", \"uid\": \"05cdec92-ac74-4112-aef2-6886f5698174\", \"id\": \"92562831\"}-->"
        }
      ],
      "component": "page",
      "_editable": "<!--#storyblok#{\"name\": \"page\", \"space\": \"139507\", \"uid\": \"6fac4f51-4f36-4e51-9855-0d192d27bfef\", \"id\": \"92562831\"}-->"
    },
    "slug": "home",
    "full_slug": "home",
    "sort_by_date": null,
    "position": 0,
    "tag_list": [
      
    ],
    "is_startpage": false,
    "parent_id": 0,
    "meta_data": null,
    "group_id": "afaf2d3c-52d8-48ee-bb95-68620467c0e0",
    "first_published_at": null,
    "release_id": null,
    "lang": "default",
    "path": "/",
    "alternates": [
      
    ],
    "default_full_slug": null,
    "translated_slugs": null
  },
  "cv": 1640132321,
  "rels": [
    
  ],
  "links": [
    
  ]
}
```

This is the Draft JSON api V2.

In my homepage I have defined just 1 component named `section` and this component has only 1 property `isFullWidth` which is `boolean`.

This is my `index.vue` code
```
<template>
  <div class="">
    <component 
      :is="state.story.content.component"
      :key="state.story.content._uid"
      :blok="state.story.content"
    />
  </div>
</template>

<script lang="ts" setup>
import { useStoryApi, useStoryBridge } from '@storyblok/nuxt/composables';

const storyApi = useStoryApi();
const route = useRoute();

const version = process.env.NODE_ENV === 'development' ? 'draft' : 'published';
const fullSlug = (route.path === '/' || route.path === '') ? 'home' : route.path;

const { data } = await storyApi.get('cdn/stories/' + fullSlug, { version: version });
const state = reactive({ story: data.story });

onMounted(() => {
  useStoryBridge(state.story.id, story => (state.story = story));
})
</script>
```

this is my `Page.vue` code

```
<template>
  <div v-editable="blok">
   <component 
      :is="blok.component"
      v-for="blok in blok.body"
      :key="blok._id"
      :blok="blok"
    />
  </div>
</template>

<script lang="ts" setup>
  const props = defineProps({
    blok: {
      type: Object,
      required: true,
    }
  });
</script>
```

and here is my `Section.vue` component code

```
<template>
  <div v-editable="blok">
  {{blok._uid}}
  </div>
</template>

<script lang="ts" setup>
const props = defineProps({
  blok: {
    type: Object,
    required: false,
  }
});
</script>
```

Trying to print the blok's `_uid` gives me the error

```
500
Cannot read properties of undefined (reading 'component')
at _sfc_ssrRender (file:///C:/JavascriptProjects/NUXT/website-ui/.nuxt/dist/server/server.mjs:3650:113)
at renderComponentSubTree (C:\JavascriptProjects\NUXT\website-ui\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:263:13)
at renderComponentVNode (C:\JavascriptProjects\NUXT\website-ui\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:214:16)
at Module.ssrRenderComponent (C:\JavascriptProjects\NUXT\website-ui\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:623:12)
at _sfc_ssrRender (file:///C:/JavascriptProjects/NUXT/website-ui/.nuxt/dist/server/server.mjs:3376:31)
at renderComponentSubTree (C:\JavascriptProjects\NUXT\website-ui\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:263:13)
at renderComponentVNode (C:\JavascriptProjects\NUXT\website-ui\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:214:16)
at Module.ssrRenderComponent (C:\JavascriptProjects\NUXT\website-ui\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:623:12)
at _sfc_ssrRender (file:///C:/JavascriptProjects/NUXT/website-ui/.nuxt/dist/server/server.mjs:3291:31)
at renderComponentSubTree (C:\JavascriptProjects\NUXT\website-ui\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:263:13)
```

but if I just print `{{ blok }}` only, the following JSON will be printed just fine 
```
{ "_uid": "05cdec92-ac74-4112-aef2-6886f5698174", 
"component": "section", 
"isFullWidth": false, 
"_editable": "<!--#storyblok#{\"name\": \"section\", \"space\": \"139507\", \"uid\": \"05cdec92-ac74-4112-aef2-6886f5698174\", \"id\": \"92562831\"}-->" }
```

I really don't understand why I cannot directly read a property from the blok object but only read the blok object as a whole.

![image](https://user-images.githubusercontent.com/4696628/147014865-bb91418d-a276-46cb-845c-d173c3bdef28.png)
![image](https://user-images.githubusercontent.com/4696628/147014896-16cde1f8-61b9-40ed-8a36-7e0106812814.png)

Any suggestions on this?

**Comment by telisjok** [comment]
I found the issue to this. It was on my code and not related to the framework.

**Comment by lianabucerzan** [comment]
Hey, @telisjok , what was the issue? I get the same error and I can't figure it out why it's happening.
